//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIET()
        {
            this.DIET_PRODUCTS = new HashSet<DIET_PRODUCTS>();
            this.USER_DIETS = new HashSet<USER_DIETS>();
        }
    
        public int DIET_ID { get; set; }
        public short KCAL { get; set; }
        public short PROTEIN { get; set; }
        public short FAT { get; set; }
        public short CARBS { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIET_PRODUCTS> DIET_PRODUCTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_DIETS> USER_DIETS { get; set; }
    }
}
