//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DietDBContext : DbContext
    {
        public DietDBContext()
            : base("name=DietDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DIET_PRODUCTS> DIET_PRODUCTS { get; set; }
        public virtual DbSet<DIET> DIETS { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTS { get; set; }
        public virtual DbSet<USER_DATA> USER_DATA { get; set; }
        public virtual DbSet<USER_DIETS> USER_DIETS { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
        public virtual DbSet<USERS_LOGS> USERS_LOGS { get; set; }
        public virtual DbSet<USERINFO> USERINFOes { get; set; }
    
        public virtual int ADDPRODUCTODIET(Nullable<decimal> pR_ID, Nullable<decimal> dT_ID, Nullable<decimal> qUANT)
        {
            var pR_IDParameter = pR_ID.HasValue ?
                new ObjectParameter("PR_ID", pR_ID) :
                new ObjectParameter("PR_ID", typeof(decimal));
    
            var dT_IDParameter = dT_ID.HasValue ?
                new ObjectParameter("DT_ID", dT_ID) :
                new ObjectParameter("DT_ID", typeof(decimal));
    
            var qUANTParameter = qUANT.HasValue ?
                new ObjectParameter("QUANT", qUANT) :
                new ObjectParameter("QUANT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADDPRODUCTODIET", pR_IDParameter, dT_IDParameter, qUANTParameter);
        }
    
        public virtual int ADDUSERLOG(Nullable<decimal> uS_ID, string dEV)
        {
            var uS_IDParameter = uS_ID.HasValue ?
                new ObjectParameter("US_ID", uS_ID) :
                new ObjectParameter("US_ID", typeof(decimal));
    
            var dEVParameter = dEV != null ?
                new ObjectParameter("DEV", dEV) :
                new ObjectParameter("DEV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADDUSERLOG", uS_IDParameter, dEVParameter);
        }
    
        public virtual int CHANGEPASSWORD(string nEW_PASSWORD, Nullable<decimal> uS_ID)
        {
            var nEW_PASSWORDParameter = nEW_PASSWORD != null ?
                new ObjectParameter("NEW_PASSWORD", nEW_PASSWORD) :
                new ObjectParameter("NEW_PASSWORD", typeof(string));
    
            var uS_IDParameter = uS_ID.HasValue ?
                new ObjectParameter("US_ID", uS_ID) :
                new ObjectParameter("US_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CHANGEPASSWORD", nEW_PASSWORDParameter, uS_IDParameter);
        }
    
        public virtual int CREATEPRODUCT(string dESCR, Nullable<decimal> kCAL, Nullable<decimal> pROTEIN, Nullable<decimal> fAT, Nullable<decimal> cARBS)
        {
            var dESCRParameter = dESCR != null ?
                new ObjectParameter("DESCR", dESCR) :
                new ObjectParameter("DESCR", typeof(string));
    
            var kCALParameter = kCAL.HasValue ?
                new ObjectParameter("KCAL", kCAL) :
                new ObjectParameter("KCAL", typeof(decimal));
    
            var pROTEINParameter = pROTEIN.HasValue ?
                new ObjectParameter("PROTEIN", pROTEIN) :
                new ObjectParameter("PROTEIN", typeof(decimal));
    
            var fATParameter = fAT.HasValue ?
                new ObjectParameter("FAT", fAT) :
                new ObjectParameter("FAT", typeof(decimal));
    
            var cARBSParameter = cARBS.HasValue ?
                new ObjectParameter("CARBS", cARBS) :
                new ObjectParameter("CARBS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATEPRODUCT", dESCRParameter, kCALParameter, pROTEINParameter, fATParameter, cARBSParameter);
        }
    
        public virtual int CREATEUSER(string uSERNAME, string pASSWORD, string uSERGENDER)
        {
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            var uSERGENDERParameter = uSERGENDER != null ?
                new ObjectParameter("USERGENDER", uSERGENDER) :
                new ObjectParameter("USERGENDER", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATEUSER", uSERNAMEParameter, pASSWORDParameter, uSERGENDERParameter);
        }
    
        public virtual int CREATEUSERDATA(Nullable<decimal> hGH, Nullable<decimal> wGH, Nullable<decimal> uS_ID)
        {
            var hGHParameter = hGH.HasValue ?
                new ObjectParameter("HGH", hGH) :
                new ObjectParameter("HGH", typeof(decimal));
    
            var wGHParameter = wGH.HasValue ?
                new ObjectParameter("WGH", wGH) :
                new ObjectParameter("WGH", typeof(decimal));
    
            var uS_IDParameter = uS_ID.HasValue ?
                new ObjectParameter("US_ID", uS_ID) :
                new ObjectParameter("US_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREATEUSERDATA", hGHParameter, wGHParameter, uS_IDParameter);
        }
    
        public virtual int DELETEPRODUCTFROMDIET(Nullable<decimal> pR_ID, Nullable<decimal> dT_ID)
        {
            var pR_IDParameter = pR_ID.HasValue ?
                new ObjectParameter("PR_ID", pR_ID) :
                new ObjectParameter("PR_ID", typeof(decimal));
    
            var dT_IDParameter = dT_ID.HasValue ?
                new ObjectParameter("DT_ID", dT_ID) :
                new ObjectParameter("DT_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DELETEPRODUCTFROMDIET", pR_IDParameter, dT_IDParameter);
        }
    
        public virtual int LOGINBYUSERNAMEPASSWORD(string uSERNAME, string pASSWORD)
        {
            var uSERNAMEParameter = uSERNAME != null ?
                new ObjectParameter("USERNAME", uSERNAME) :
                new ObjectParameter("USERNAME", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LOGINBYUSERNAMEPASSWORD", uSERNAMEParameter, pASSWORDParameter);
        }
    }
}
