//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIET_PRODUCTS
    {
        public int PRODUCT_ID { get; set; }
        public int DIET_ID { get; set; }
        public short QUANTITY { get; set; }
    
        public virtual DIET DIET { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
