//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.DIET_PRODUCTS = new HashSet<DIET_PRODUCTS>();
        }
    
        public int PRODUCT_ID { get; set; }
        public string PRODUCT_DESCRIPTION { get; set; }
        public short KCAL_100 { get; set; }
        public short PROTEIN_100 { get; set; }
        public short FAT_100 { get; set; }
        public short CARBS_100 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIET_PRODUCTS> DIET_PRODUCTS { get; set; }
    }
}
