//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_DATA
    {
        public int USER_ID { get; set; }
        public short HEIGHT { get; set; }
        public decimal WEIGHT { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public int USER_DATA_ID { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
