//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERINFO
    {
        public string USER_NAME { get; set; }
        public string GENDER { get; set; }
        public System.DateTime REG_DATE { get; set; }
        public short RECENT_HEIGHT { get; set; }
        public decimal RECENT_WEIGHT { get; set; }
    }
}
